//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSTUDIO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLSTUDIOEntities : DbContext
    {
        public QLSTUDIOEntities()
            : base("name=QLSTUDIOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Attendance> Attendance { get; set; }
        public virtual DbSet<DanceRoom> DanceRoom { get; set; }
        public virtual DbSet<DanceType> DanceType { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
    }
}
